version: "3.9"

services:
  nationservice:
    container_name: nationservice
    hostname: nationserviceHost
    build: ./Node-Service-Nationalize
    image: "${DOCKERHUBNAME}/nationservice:${TAG}"
    ports:
      - "3001:3001"
      - "23001:19999"
      
  genderservice:
    container_name: genderservice
    hostname: genderserviceHost
    build: ./Node-Service-Genderize
    image: "${DOCKERHUBNAME}/genderservice:${TAG}"
    ports:
      - "3002:3002"
      - "23002:19999"

  blazorserviceguessmyui:
    container_name: blazorserviceguessmyui
    hostname: blazorserviceguessmyuiHost
    build: ./Blazor-Service-GuessMyUI
    image: "${DOCKERHUBNAME}/blazorserviceguessmyui:${TAG}"
    environment:
      - NATIONSERVICEIP=nationserviceHost
      - NATIONSERVICEPORT=3001
      - GENDERSERVICEIP=genderserviceHost
      - GENDERSERVICEPORT=3002     
    ports:
      - "80:80"
      - "20080:19999"    

  influxdb:
    image: influxdb
    hostname: influxdbHost
    volumes:
      - 'influxdb-storage:/var/lib/influxdb'
    ports:
      - '8086:8086'
    restart: always

  grafana:
    image: grafana/grafana
    hostname: grafanaHost
    volumes:
      - 'grafana-storage:/var/lib/grafana'
    environment:
      - GF_AUTH_ANONYMOUS_ENABLED=true
    ports:
      - '3000:3000'
    restart: always
volumes:
  grafana-storage:
  influxdb-storage:          