{
 "title": "GuessMy",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "UI Network",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "target": "netdata.guessMyUI.net.eth0.received"
    },
    {
     "target": "netdata.guessMyUI.net.eth0.sent"
    }
   ]
  },
  {
   "title": "CPU",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "target": "netdata.guessMyUI.cpu.cpu0.user"
    },
    {
     "target": "netdata.nationalizeService.cpu.cpu0.user"
    },
    {
     "target": "netdata.genderService.cpu.cpu0.user"
    }
   ]
  },
  {
   "title": "UI RAM",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "target": "netdata.guessMyUI.system.ram.used"
    }
   ]
  },
  {
   "title": "netdata CPU",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "targets": [
    {
     "target": "netdata.genderService.apps.cpu_user.netdata"
    },
    {
     "target": "netdata.nationalizeService.apps.cpu_user.netdata"
    }
   ]
  }
 ]
}