name: docker-compose-push-test-action

on: push

jobs:
  build-container:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        
      - name: Build and run stack
        run: docker-compose --env-file .env.test up -d        
        
      - name: Test
        run: docker run --network container:blazorserviceguessmyui appropriate/curl -s --retry 10 --retry-connrefused http://localhost:80/
        
      - name: Wind down stack
        run: docker-compose down            
        
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_PASSWORD }}
          
      - name: Push to docker hub
        run: docker-compose push          
