name: docker-compose-push-test-action

on: push

jobs:

  build-container:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install cosign except on PRs
        if: github.event_name != 'pull_request'
        uses: sigstore/cosign-installer@main 
        with:
          cosign-release: 'v1.4.0'

      - name: Build and run stack
        run: docker-compose --env-file .env.test up -d        
        
      - name: Test
        run: docker run --network container:blazorserviceguessmyui appropriate/curl -s --retry 10 --retry-connrefused http://localhost:80/
        
      - name: Wind down stack
        run: docker-compose --env-file .env.test down            
        
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_PASSWORD }}
          
      - name: Push to docker hub
        run: docker-compose --env-file .env.test push        

      # Sign the resulting Docker image digest except on PRs.
      - name: Write signing key to disk (only needed for `cosign sign --key`)
        if: ${{ github.event_name != 'pull_request' }}
        run: echo "${{ secrets.COSIGN_KEY }}" > cosign.key
        
      - name: Sign container image
        if: ${{ github.event_name != 'pull_request' }}
        run: |
          cosign sign --key cosign.key rainan/nationservice:test
        env:
          COSIGN_PASSWORD: "${{ secrets.COSIGN_PASSWORD }}" 

      - name: Verify signing
        run: cosign verify --key .github/workflows/cosign.pub rainan/nationservice:test
